### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by koufopoulosf** [nverbeek/nats_client_flutter#2]
Hello 👋

First of all I would like to thank you for this beautiful repo, it seems very interesting :)

The reason I am opening this issue is basically to ask this question.

Based on your valuable experience with NATS on Flutter, would you say that the available packages ([outdated and only this one](https://github.com/chartchuo/dart-nats)), are suitable for making a realtime chat app in flutter, for a production solution? Meaning like a whatsapp kind of app, that may require many concurrent connections... or would you suggest a websockets based solution which is generally more supported? Nats seems to solve the scalability issue (server's side problems), but client wise, I'm not sure if current flutter packages are of any help for making a realtime chat app, that is production ready.

I would really appreciate your feedback over this matter.

Kind regards,
koufopoulosf

**Comment by nverbeek** [comment]
Hello, @koufopoulosf, great question! I'll try my best to answer this.

First off, I do want to mention there is another library available for NATS on Dart: [nats_client](https://github.com/dgofman/nats_client). This particular library seems to be better maintained and supports way more security features than dart_nats. My memory is that nats_client supports only WebSocket (`ws://`) NATS connections, however. For this client I was making, I wanted to support non-web socket connections to NATS, and so I was limited to dart_nats. At a minimum, you could take a look at this alternative library and see if it better meets your needs or not.

I do agree that NATS is excellent from a server side/cloud perspective and can definitely scale for a chat app. I also agree that Flutter is a good framework for an app like that, since you should be able to support every single major platform from one codebase. Your real question is - are either of these Dart NATS libraries production ready for a chat app? If your app can utilize a WebSocket NATS connection, I think nats_client is probably close to production ready. This is also the [officially recognized client for Dart by nats.io](https://nats.io/download/). For dart_nats, I'd be more wary of using that in a production setting. However, the maintainer of that is open to contributions, so perhaps you could add the features you need yourself and contribute them back to the community.

I hope this helps you make your decision! Thanks for reaching out.

**Comment by koufopoulosf** [comment]
Hello @nverbeek , thank you for your detailed response, I highly appreciate it! To be honest, I thought nats_client was outdated, since it's been almost a year with no updates. However you are totally right, I will give nats_client a try!

Thank you once again for your detailed reply🙏. I just found out about nats, and it seems a wonderful tech ✌️
